import mongoose, { Schema } from "mongoose";

const feedbackSchema = new Schema({
  weekNumber:{
      type:Number,
      default:0
  },
  creator:{
      type:Schema.Types.ObjectId,
      ref:"User"
  },
  outfitChoice:{
    type:String,
    default:"None"
  },
  priceRange:{
    type:String,
    default:"None"
  },
  topPurchased:{
    type:String,
    default:"no"
  },
  bottomPurchased:{
    type:String,
    default:"no"
  },
  shoesPurchased:{
    type:String,
    default:"no"
  },
  wasGoodIcon:{
    type:String,
    default:"no"
  },
  iconFeedback:{
    type:String,
    default:"None"
  },
  didPurchasedIconPiece:{
    type:String,
    default:"no"
  },
  iconPiecesPurchased:{
    type:[String],
    default:[]
  },
  localFeedback:{
    type:String,
    default:"None"
  },
  goodLocalPick:{
    type:String,
    default:"None"
  },
  timestamp:{
    type:Date,
    default:Date.now()
  },
});

export default mongoose.models.Feedback || mongoose.model("Feedback", feedbackSchema);
